name: Create release
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, 'skip-release')
    uses: libops/.github/.github/workflows/bump-release.yaml@8e27d95846671a9e319f1900e86a488a1d4f39b3
    with:
      workflow_file: goreleaser.yaml
    permissions:
      contents: write
      actions: write
