name: build-push-ar
on:
  push:
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: '>=1.23.4'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6
        with:
          version: latest
      
      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v

      - name: Test with the Go CLI
        run: go test -v -race ./...


  build-push-ar:
    needs: [test]
    uses: libops/actions/.github/workflows/build-push.yml@main
    with:
      image: "shared/vault-init"
    permissions:
      contents: read
      id-token: write
    secrets: inherit
